"""
Shared data schemas for the J26-DS-358 pipeline.

Data flow:
  User → Pipeline API
  Pipeline API → Member 3 (get routing)
  Pipeline API → Member 1 (retrieve candidates)   [uses routing from M3]
  Pipeline API → Member 2 (harmonize candidates)  [uses M1 output]
  Pipeline API → Member 4 (re-rank + normalize)   [uses M2 output]
  Pipeline API → User (final results)

AGREED BY: All four members
LAST UPDATED: 2026-08-10
DO NOT CHANGE WITHOUT TEAM AGREEMENT.
"""

from pydantic import BaseModel, Field
from typing import List, Dict, Any
from enum import Enum


# Shared Enums

class QueryType(str, Enum):
    """The three query types classified by Member 1."""
    EXACT    = "exact"     # "Samsung A55 256GB" — user knows exactly what they want
    SEMANTIC = "semantic"  # "gaming phone good battery" — user has a need, not a product
    HYBRID   = "hybrid"    # "cheap phone under 60000" — semantic + price constraint


class Platform(str, Enum):
    """E-commerce platforms the system can retrieve from."""
    EBAY        = "ebay"
    ALIEXPRESS  = "aliexpress"
    ESCI        = "esci"           # Amazon ESCI benchmark dataset (for evaluation)


class Category(str, Enum):
    """Product categories in scope for this project."""
    ELECTRONICS = "electronics"
    FASHION     = "fashion"


# Pipeline API Input (User → Pipeline)

class QueryRequest(BaseModel):
    """Input to the main /search endpoint."""
    query: str = Field(
        min_length=1,
        max_length=500,
        description="Natural language shopping query from the user",
        example="gaming phone good battery under 60000"
    )
    max_results: int = Field(
        default=10,
        ge=1,
        le=50,
        description="Maximum number of products to return"
    )
    categories: List[Category] = Field(
        default=[Category.ELECTRONICS, Category.FASHION],
        description="Categories to search within"
    )


# Member 3 → Member 1 (Platform Routing)

class PlatformRoute(BaseModel):
    """A single platform with its routing metadata from the knowledge graph."""
    platform: Platform
    category_relevance: float = Field(
        ge=0.0, le=1.0,
        description="How relevant this platform is for the given category (0=irrelevant, 1=highly relevant)"
    )
    staleness_score: float = Field(
        ge=0.0, le=1.0,
        description="How stale the data might be (0=fresh, 1=very stale — needs re-fetch)"
    )


class RoutingDecision(BaseModel):
    """
    Member 3 output → Member 1 input.
    Tells Member 1 which platforms to query and how relevant each is.
    """
    query_id: str
    category: Category
    platforms_to_query: List[PlatformRoute] = Field(
        description="Ordered list of platforms to retrieve from, most relevant first"
    )

# Member 1 → Member 2 (Retrieval Candidates)

class RawProduct(BaseModel):
    """
    A single product candidate from one platform.
    This is the raw, unprocessed product as returned by the platform API.
    """
    product_id: str = Field(description="Platform's own product ID")
    platform: Platform
    title: str
    price: float
    currency: str = Field(description="ISO 4217 currency code, e.g. LKR, USD, INR")
    retrieval_score: float = Field(
        ge=0.0,
        description="Blended retrieval score from Member 1's confidence-weighted search"
    )
    rank: int = Field(ge=1, description="Rank in Member 1's result list")
    raw_attributes: Dict[str, Any] = Field(
        default_factory=dict,
        description="All attributes as returned by the platform (not yet harmonized)"
    )


class RetrievalResult(BaseModel):
    """
    Member 1 output → Member 2 input.
    Contains 50-100 raw candidate products.
    """
    query_id: str
    query: str
    query_type: QueryType
    alpha: float = Field(
        ge=0.0, le=1.0,
        description="BM25 confidence weight; (1-alpha) is the HyDE dense weight"
    )
    hypothetical_spec: str = Field(
        description="The product specification generated by Member 1's HyDE model"
    )
    candidates: List[RawProduct] = Field(
        description="Raw product candidates, ordered by retrieval_score descending"
    )

# Member 2 → Member 4 (Harmonized Products)

class PlatformPrice(BaseModel):
    """A price as listed on one specific platform."""
    platform: Platform
    price: float
    currency: str


class HarmonizedProduct(BaseModel):
    """
    A deduplicated, schema-harmonized product.
    Multiple raw listings from different platforms that refer to the same
    physical product are merged into a single HarmonizedProduct.
    """
    canonical_id: str = Field(
        description="Member 2's generated ID for this unique product"
    )
    canonical_title: str = Field(
        description="Cleaned, unified product title"
    )
    platforms: List[Platform] = Field(
        description="All platforms where this product was found"
    )
    prices: List[PlatformPrice] = Field(
        description="Prices across all platforms where found"
    )
    harmonized_attributes: Dict[str, Any] = Field(
        description="Unified attribute schema: keys are standardised (e.g. 'ram_gb', 'storage_gb', 'brand')"
    )
    retrieval_score: float = Field(
        description="Best retrieval score from Member 1 across all matched listings"
    )
    source_product_ids: List[str] = Field(
        default_factory=list,
        description="Original product IDs from Member 1 that were merged into this product"
    )


class HarmonizationResult(BaseModel):
    """
    Member 2 output → Member 4 input.
    Deduplicated and harmonized. Typically 10-30 unique products.
    """
    query_id: str
    query: str
    products: List[HarmonizedProduct]
    total_candidates_received: int = Field(
        description="How many raw candidates Member 2 received from Member 1"
    )

# Member 4 → User (Final Ranked Results)

class RankedResult(BaseModel):
    """A single product in the final ranked list shown to the user."""
    rank: int = Field(ge=1)
    canonical_id: str
    canonical_title: str
    platform: Platform = Field(description="Best platform to buy from")
    original_price: float
    currency: str
    ppp_adjusted_price_usd: float = Field(
        description="Price adjusted for local purchasing power, expressed in USD-equivalent"
    )
    relevance_score: float = Field(
        ge=0.0, le=1.0,
        description="Cross-encoder relevance score (how well this product matches the query)"
    )
    harmonized_attributes: Dict[str, Any] = Field(
        description="Standardised product attributes for display"
    )


class FinalResponse(BaseModel):
    """
    Member 4 output → API response to the user.
    This is what the frontend/demo sees.
    """
    query_id: str
    query: str
    query_type: QueryType
    hypothetical_spec: str = Field(description="The product spec Member 1 generated — useful for debugging")
    results: List[RankedResult]
    total_candidates_retrieved: int
    total_unique_products: int
    platforms_queried: List[Platform]